### ISSUE TITLE
Hide unneeded sectors in profile chart

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#100]
In Eichstätt, we don't have the "Theorizing" items, but the profile chart still shows the empty sector.
Is it possible to hide sectors if no items are present in a specific category?
(In this case: If there are no items starting with `P_Theorizing`)

(If it is too complicated, we leave it for the moment)

**Comment by alpkaanaksu** [comment]
```yaml
score_categories:
  - title: "Theorizing & Formal Modeling"
    cue: "Theorizing"

  - title: "Open Data"
    cue: "Data"

  - title: "Open Materials"
    cue: "OpenMaterials"

  - title: "Preregistration"
    cue: "Prereg"
    
  - title: "Reproducible Code & Verification"
    cue: "ReproducibleScripts|IndependentVerification"
```

I moved the categories to config.yaml.

`title` is the name that is visible in the score box (e.g. in the legend).

An indicator belongs to a category if the id contains `cue`. This is simply RegEx matching, so you can use `|` for 'or'.

You can remove the category from RESQUE Eichstätt by deleting the corresponding item from the list.

**Comment by nicebread** [comment]
Thanks, this is a smart solution!

**Comment by nicebread** [comment]
Just a minor thing: The colors change, e.g. when I remove "Theorizing":

<img width="366" alt="Image" src="https://github.com/user-attachments/assets/3e787980-d199-4552-9cd7-d4d5b3500468" />

<img width="382" alt="Image" src="https://github.com/user-attachments/assets/0857a127-ef73-4b2f-a788-fe28524b18ec" />

Ideally, they stay the same. Maybe we also define the colors in the config.yaml?

**Comment by alpkaanaksu** [comment]
Done. c40764de0af38782dfc16ef7bd671dcc2b59b60f

I added the colors to config.yaml. They are used when rendering the score charts and the legend.

```yaml
score_categories:
  - title: "Theorizing & Formal Modeling"
    cue: "Theorizing"
    color: '#7fb1d3'

  - title: "Open Data"
    cue: "Data"
    color: '#8ed3c7'

  - title: "Open Materials"
    cue: "OpenMaterials"
    color: '#efd59d'

  - title: "Preregistration"
    cue: "Prereg"
    color: '#bebada'

  - title: "Reproducible Code & Verification"
    cue: "ReproducibleScripts|IndependentVerification"
    color: '#fb8072'
```
