### ISSUE TITLE
Alp: Add your author information to CITATION.cff

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#125]
https://github.com/RESQUE-Framework/website/blob/a087251ad42e6489426c7fbdfe282dbb6a5e627a/CITATION.cff

**Comment by alpkaanaksu** [comment]
I am already in the CITATION.cff for this repo. Should I add myself to the website repo too?

And if yes, where?

Can you add it?

```yaml
 - given-names: Alp Kaan
    family-names: Aksu
    email: hi@alpkaanaksu.com
    orcid: 'https://orcid.org/0009-0007-7165-430X'
```
