### ISSUE TITLE
Allow multiple versions of the packs

### ISSUE THREAD

**Issue by nicebread** [RESQUE-Framework/collector-app#94]
In the future, there probably will be multiple versions of the packs, e.g. `core-pubs-clinical.json`.
Can we have a mechanism, where in a config file (probably `config/config.yaml`) the path to the desired pack is given?

Default:

```yaml
pubs: packs/core-pubs.json
```

Customized:

```yaml
pubs: packs/core-pubs-clinical.json
```

**Comment by nicebread** [comment]
In fact, we need this feature rather sooner than later, so tagged this with "urgent".

**Comment by alpkaanaksu** [comment]
I moved the config out of menu.js into config.yaml

```yaml
meta:
  sources: ["packs/core-meta.json"]
  exclude: ["LastName"]
  config:
    min_indicators_warning_threshold: 0

pubs:
  sources: ["packs/core-pubs.json"]
  include: ["DOI"]
  config:
    min_indicators_warning_threshold: 0
```

`sources` includes the packs that should be combined. E.g. if there are extension packs, we could do somethink like:

```yaml
pubs:
  sources: ["packs/core-pubs.json", "packs/extensions/clinical-psych-pubs.json"]
```

The elements from that 'pack' would be included (hopefully, we should test this) in our final 'pubs form.

If `exclude` is provided, we exclude the indicators with the ids from the list. We include everything else per default.

If `include` is provided, we include the indicators with the ids from the list. We exclude everything else per default.

If `exclude` and `include` both do not exist, we pick everything.

I tested it with the YAML I copied here, results:

<img width="654" alt="Image" src="https://github.com/user-attachments/assets/7213749e-cc17-4518-b68e-66153df6b7e4" />

No lastname, because `exlude: ["LastName"]`.

<img width="659" alt="Image" src="https://github.com/user-attachments/assets/691d4184-dcf8-4a3c-8e75-3e6b8afa302f" />

Only DOI field, because `include: ["DOI"]`

**Comment by nicebread** [comment]
Nice approach!
One difficulty could be that some expansion pack items ideally should be interspersed with the default items. (and not one block at the end of the survey). But I see no easy solution for that ...

**Comment by alpkaanaksu** [comment]
I tested extension packs:

```yaml
pubs:
  sources: ["packs/core-pubs.json", "packs/extensions/clin-pubs.json"]
  include: ["DOI", "CP_Hello"]
  config:
    min_indicators_warning_threshold: 0
```

<img width="654" alt="Image" src="https://github.com/user-attachments/assets/0e012fee-1a0f-4af3-93c8-eb5db3d2cf82" />
